license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="icon.png"
authors="Fatih Aykut"
description='''
A rechargeable teleportation device with saved destination slots and hotkey teleporting.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    reason="Allows teleport devices to be equipped in a Curios teleport slot and used through keybinds."
    versionRange="[15.0.0-beta.2,)"
    ordering="AFTER"
    side="BOTH"
